### PR TITLE
🐴 <button onclick="alert('🐴')">🐴</button>

### PR DESCRIPTION
**Pull request by samccone**
words
are
fun

### CODE REVIEW

**Comment by TheAlphaNerd** [comment]
Oh yeah... that readme thing is kinda important

**Comment by samccone** [comment]
i feel so OS

**Comment by TheAlphaNerd** [comment]
I love the attention to title detail

**Comment by TheAlphaNerd** [comment]
we should probs abstract this to a lib that can spit out any generic live captioning stream.

Then each conf module can literally be a one liner :P

**Comment by samccone** [comment]
probs

But I do like the infinite forking
feels more artisanal 
hand crafted bespoke OS

**Comment by TheAlphaNerd** [comment]
Unfortunately there is no fork emoji without a knife, so this will have to do

                🍴🍴🍴🍴🍴🍴🍴🍴🍴🍴🍴🍴🍴🍴🍴🍴🍴🍴🍴
                🎶🎶🎶🎶    TOO MANY FORKS   🎶🎶🎶🎶
                🍴🍴🍴🍴🍴🍴🍴🍴🍴🍴🍴🍴🍴🍴🍴🍴🍴🍴🍴

**Pull request merged**
